directories:
  local_file: "data/travel2.sqlite"
  backup_file: "data/travel2.backup.sqlite"

urls:
  travel_db_url: https://storage.googleapis.com/benchmarks-artifacts/travel-db/travel2.sqlite
  swiss_faq_url: https://storage.googleapis.com/benchmarks-artifacts/travel-db/swiss_faq.md

openai_models:
  model: gpt-4-turbo
  # model: gpt-3.5-turbo-0125
  embedding_model: text-embedding-3-small

RAG:
  k: 2
  tavily_search_max_results: 1

langsmith:
  tracing: "true"
  project_name: "Brook AI"
